kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: demo-cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/lib/docker/volumes/kind-mongo-data/_data
        containerPath: /data/mongo
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP